# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./backend
      run: swift build -v
    - name: Test
      working-directory: ./backend
      run: swift test -v
